<a href="https://colab.research.google.com/github/karthik0311/Machine-Learning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook , we will cover fundamentals of imortant concepts of tensors using tensorflow.

Specifically, we will cover:
* Intro to tensors
* getting info from tensors
* manipulating tensors
* Tensors and Numpy
* using @tf.func(a way to speed up your regular python functions)
* Using GPUs with Tensorflow
* Exercises to try


# Introduction to Tensors

In [2]:
# import tensors
import tensorflow as tf
print(tf.__version__)

2.4.1


In [3]:
# Create tensors wth tf.constant
# https://www.tensorflow.org/api_docs/python/tf/constant
# tf.constant(value, dtype=None, shape=None, name='Const')
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# check the no of dimensions of a tensor

scalar.ndim

0

In [5]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# checkdimesion of vector
vector.ndim


1

In [7]:
# create matrix
matrix = tf.constant([[10,7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [11]:
# create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the data type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [12]:
another_matrix.ndim

2

In [13]:
# lets create tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [14]:
tensor.ndim

3

what we created so far:

* scalar : a single number
* vector : a number with direction( eg : wind speed and direction)
* matrix : a 2- dimensional array of numbers
* Tesnor : an N - Dimensional array of numbers (n - can be any number , a 0 - dimensional tensor is a scalar, 1 - dimensional tensor is vector)

### creating tensors with tf.variable
https://www.tensorflow.org/api_docs/python/tf/Variable

tf.Variable(
    initial_value=None, trainable=None, validate_shape=True, caching_device=None,
    name=None, variable_def=None, dtype=None, import_scope=None, constraint=None,
    synchronization=tf.VariableSynchronization.AUTO,
    aggregation=tf.compat.v1.VariableAggregation.NONE, shape=None
)

In [15]:
# create same tensor with tf,variable() as above
changeable_tensor =  tf.Variable([10, 7])
unchangeable_tensor =  tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [23]:
# lets try change one of elements in our changeable  tensor
changeable_tensor[0] = 7.0

TypeError: ignored

In [24]:
# need to try with .assign()

changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [25]:
#lets try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor


AttributeError: ignored

Note : Rarely in practice will you need to decide whether t use tf.constant or tf.variable to create tensors as TensorFlow does for you. However , if in doubt , use tf.constant and change it later if needed

### creating random tensors

Random tensors are tensors of some abitrary size which contain random numbers

In [28]:
# create two random (but the same tensors)
# tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None)
# https://www.tensorflow.org/api_docs/python/tf/random/uniform

random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_1
random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_2 = random_2.normal(shape=(3, 2))
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)