<a href="https://colab.research.google.com/github/karthik0311/Machine-Learning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook , we will cover fundamentals of imortant concepts of tensors using tensorflow.

Specifically, we will cover:
* Intro to tensors
* getting info from tensors
* manipulating tensors
* Tensors and Numpy
* using @tf.func(a way to speed up your regular python functions)
* Using GPUs with Tensorflow
* Exercises to try


# Introduction to Tensors

In [55]:
# import tensors
import tensorflow as tf
print(tf.__version__)

2.4.1


In [56]:
# Create tensors wth tf.constant
# https://www.tensorflow.org/api_docs/python/tf/constant
# tf.constant(value, dtype=None, shape=None, name='Const')
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [57]:
# check the no of dimensions of a tensor

scalar.ndim

0

In [58]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [59]:
# checkdimesion of vector
vector.ndim


1

In [60]:
# create matrix
matrix = tf.constant([[10,7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [61]:
matrix.ndim

2

In [62]:
# create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the data type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [63]:
another_matrix.ndim

2

In [64]:
# lets create tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [65]:
tensor.ndim

3

what we created so far:

* scalar : a single number
* vector : a number with direction( eg : wind speed and direction)
* matrix : a 2- dimensional array of numbers
* Tesnor : an N - Dimensional array of numbers (n - can be any number , a 0 - dimensional tensor is a scalar, 1 - dimensional tensor is vector)

### creating tensors with tf.variable
https://www.tensorflow.org/api_docs/python/tf/Variable

tf.Variable(
    initial_value=None, trainable=None, validate_shape=True, caching_device=None,
    name=None, variable_def=None, dtype=None, import_scope=None, constraint=None,
    synchronization=tf.VariableSynchronization.AUTO,
    aggregation=tf.compat.v1.VariableAggregation.NONE, shape=None
)

In [66]:
# create same tensor with tf,variable() as above
changeable_tensor =  tf.Variable([10, 7])
unchangeable_tensor =  tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [67]:
# lets try change one of elements in our changeable  tensor
changeable_tensor[0] = 7.0

TypeError: ignored

In [ ]:
# need to try with .assign()

changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
#lets try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor


Note : Rarely in practice will you need to decide whether t use tf.constant or tf.variable to create tensors as TensorFlow does for you. However , if in doubt , use tf.constant and change it later if needed

### creating random tensors

Random tensors are tensors of some abitrary size which contain random numbers

In [68]:
# create two random (but the same tensors)
# tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None)
# https://www.tensorflow.org/api_docs/python/tf/random/uniform

random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_1
random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_2 = random_2.normal(shape=(3, 2))
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### shuffle the order of elements in tensor

In [72]:
# shuffle the tensor (valuable for when you want to shuffle your data so the inherent order doesnot effect learning)
# https://www.tensorflow.org/api_docs/python/tf/random/shuffle
not_shuffled = tf.constant([[10, 7],
                             [3, 4],
                             [2, 5]])
not_shuffled.ndim
#shuffle our non-shuffled tensor
# https://www.tensorflow.org/api_docs/python/tf/random/set_seed
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
not_shuffled

https://www.tensorflow.org/api_docs/python/tf/random/set_seed

It looks like if we want oue shuffled tensors to be in the same order , we 've
got to use the global level random seed as well as the operation level random seed

Rule 4 : If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [ ]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42)# operation level random seed

### other ways to make tensors

In [ ]:
# create a tensor for all ones
tf.ones([10, 7])

In [ ]:
# create tensor for all zeros
tf.zeros(shape=(3, 4))

### Turn Numpy array into tensors

The main difference between numpy array and tensorflow tensors is that tensors can be run on a GPU(Much faster for numerical computing)

In [ ]:
# turn numpy array into tensors

import numpy as np
numpy_A = np.arange(1, 25,dtype=np.int32)
numpy_A

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))

B = tf.constant(numpy_A)
A, B

### Geting information from tensors

when dealing with tensors you probably want to be aware of the following attributes :

* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
# create a rank 4 tensor (4 Dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
# get various attributes of our tensor

print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimesnions(rank):", rank_4_tensor.ndim)
print("shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))

### Getting Tensors

Tensors can be indexed just like python lists

In [78]:
some_list = [1, 2, 3, 4] 
some_list[:2]

[1, 2]

In [79]:
#get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [81]:
# get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [82]:
# create a rank 2 tensor
rank_2_tensor = tf.constant ([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [83]:
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [84]:
# get last item of each row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [85]:
# add in extra dimesnion to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [86]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [87]:
# alternative to tf.newaxis
# https://www.tensorflow.org/api_docs/python/tf/expand_dims
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [88]:
tf.expand_dims(rank_2_tensor,axis =0) # expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### manipulating tensors(tensor operations)

**BASIC Operations**
+-/*

In [89]:
# you can add values to a tensor using addition operator
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor + 10 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [90]:
# original tensor is unchanged

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [91]:
# multiplication also works 
tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [92]:
# substraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

### chnging datatype of tensor

In [93]:
# create a new tensor with default datatype (float 32)
# https://www.tensorflow.org/api_docs/python/tf/cast
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [94]:
c = tf.constant([10, 7])
c.dtype

tf.int32

In [95]:
# change from float 32 to float 16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

### Agrregating tensors

Aggregating tensors = considering them from multiple values down to a smaller amount of values

In [97]:
# get the absolute values

D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [98]:
# get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let go thru the following forms of aggregation
* get minimum
* get maximum
* get mean of tensor
* get sum of tensor

In [99]:
# create random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([94, 20, 60, 97, 62, 30, 79, 84,  8, 53,  8,  9, 73, 19, 45, 19, 23,
       87, 64, 56, 83, 60, 67, 41, 19, 45, 12, 26, 94, 97, 46, 91, 74, 56,
       80, 32, 52, 35, 97, 75, 13, 35, 66,  7, 78, 42, 37, 68, 23, 40])>

In [100]:
tf.size(E),E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [102]:
# find minimum
min = tf.reduce_min(E)
min

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [103]:
# find maximum
max = tf.reduce_max(E)
max

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [104]:
# find mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [105]:
#find sum

tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2581>

In [109]:
# find variance of tensor
tf.reduce_variance(E) # wont work
#https://www.tensorflow.org/probability/api_docs/python/tfp/stats/variance#:~:text=Estimate%20variance%20using%20samples.&text=%23%20var%5Bi%2C%20j%5D,j)%20batch%20member%20of%20x.&text=Notice%20we%20divide%20by%20N,1%20%2C%20but%20is%20slightly%20biased.

AttributeError: ignored

In [108]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=775>

In [112]:
# find standard deviation
# https://www.tensorflow.org/api_docs/python/tf/math/reduce_std
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.84018>

### finding the positional of the maximum and minimum

In [114]:
# create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [115]:
# find positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [118]:
#index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [119]:
#find max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [121]:
# check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [122]:
# find th positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [123]:
# find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### squeezing a tensor(removing all single dimensions)

In [126]:
# create a tensor to get started
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [127]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [128]:
G_squeezed = tf.squeeze(G)

In [129]:
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>, TensorShape([50]))

### One hot encoding

In [131]:
# create list on indices
some_list = [0, 1, 2, 3]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [132]:
# specify custom values for one hot encoding
tf.one_hot(some_list, depth = 4,on_value="i love", off_value="i hate" )

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'i love', b'i hate', b'i hate', b'i hate'],
       [b'i hate', b'i love', b'i hate', b'i hate'],
       [b'i hate', b'i hate', b'i love', b'i hate'],
       [b'i hate', b'i hate', b'i hate', b'i love']], dtype=object)>

📖 00 TensorFlow Fundamentals Extra-curriculum
Read through the list of TensorFlow Python APIs, pick one we haven't gone through in this notebook, reverse engineer it (write out the documentation code for yourself) and figure out what it does.
Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
How would you calculate your grocery bill for the month and for the year using tensors?
Go through the TensorFlow 2.x quick start for beginners tutorial (be sure to type out all of the code yourself, even if you don't understand it).
Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?
Watch the video "What's a tensor?" - a great visual introduction to many of the concepts we've covered in this notebook.